services:
    db:
        container_name: db
        image: postgres
        environment:
            POSTGRES_USER: db_user
            POSTGRES_PASSWORD: db_user_pass
            POSTGRES_DB: cleanarchitecture
        restart: always
        volumes:
            - ./.containers/database:/var/lib/postgresql
        ports:
            - 5432:5432

    api:
        container_name: api
        image: ${DOCKER_REGISTRY-}cleanarchitectureapi
        build:
            context: .
            dockerfile: src/CleanArchitecture.Api/Dockerfile
        environment:
            ASPNETCORE_ENVIRONMENT: Test
            ASPNETCORE_HTTP_PORTS: 8080
        ports:
            - 8080:8080
            - 8081:8081
        depends_on:
          - db
    
    serilogseq:
        container_name: serilogseq
        image: datalust/seq:2023.4
        environment:
            ACCEPT_EULA: Y
        ports:
            - 5341:5341
            - 8082:80
     
