
@BaseUrl = http://localhost:5015



POST {{BaseUrl}}/api/Alquileres
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZjA3YzAwYy1mODE3LTQyOTAtOTZiNC1mZjE5OTlmZTY0MzIiLCJlbWFpbCI6ImZhY3VAZXhhbXBsZS5jb20iLCJleHAiOjE3NjA4MTc1NDIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAxNSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAxNSJ9.KC6xebvdT3Voao2C9Wf3vxzIKBRDzE0IwgeVQWa1Do4

{
    "vehiculoId": "30fb2b42-036b-4de6-b3d3-fd5c99c14631",
    "userId": "30fb2b42-036b-4de6-b3d3-fd5c99c14631",
    "desde": "2025-10-12",
    "hasta": "2025-12-12"
}

###

POST {{BaseUrl}}/api/users
Accept: application/json
Content-Type: application/json

{
    "email": "facu22@example.com",
    "nombre": "facu",
    "apellido": "facu",
    "password": "susPassword"
}



###
@name login
POST {{BaseUrl}}/api/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test"
}

###

###
@name login
POST {{BaseUrl}}/api/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test"
}

###


###
POST {{BaseUrl}}/api/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "admin"
}


### 
GET {{BaseUrl}}/api/vehiculos?desde=2025-10-01&hasta=2025-12-01
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5OTc3OTNhOC0wNjg4LTRmOWItOWRkZC02ZTk4NGFlMGM1NGEiLCJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwicGVybWlzc2lvbnMiOlsiUmVhZFVzZXIiLCJXcml0ZVVzZXIiLCJVcGRhdGVVc2VyIl0sImV4cCI6MTc2MTAzNTk1MCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDE1IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDE1In0.ciqDB8dKvQVTKuIx5UIiowmJpgVJksG-vAfO-uTbA-I

###

###
GET {{BaseUrl}}/api/vehiculos/paginated?pageIndex=1&pageSize=2&sort=modeloDesc&modeloFilter=tau
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OTg1NTlmNy1jZGViLTQyNTEtYjIwMi05MzUwZTk4ZTUzMDAiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJwZXJtaXNzaW9ucyI6IlJlYWRVc2VyIiwiZXhwIjoxNzYxNzE2NDc3LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMTUiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUwMTUifQ.JDuCI2yiW_5k0JAeQuEg_lCryj2XsYOh0nUO3-Jg3T4
###
