@BaseUrl = http://localhost:5015



POST {{BaseUrl}}/api/Alquileres
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZjA3YzAwYy1mODE3LTQyOTAtOTZiNC1mZjE5OTlmZTY0MzIiLCJlbWFpbCI6ImZhY3VAZXhhbXBsZS5jb20iLCJleHAiOjE3NjA4MTc1NDIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAxNSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAxNSJ9.KC6xebvdT3Voao2C9Wf3vxzIKBRDzE0IwgeVQWa1Do4

{
    "vehiculoId": "30fb2b42-036b-4de6-b3d3-fd5c99c14631",
    "userId": "30fb2b42-036b-4de6-b3d3-fd5c99c14631",
    "desde": "2025-10-12",
    "hasta": "2025-12-12"
}

###

POST {{BaseUrl}}/api/users
Accept: application/json
Content-Type: application/json

{
    "email": "facu@example.com",
    "nombre": "facu",
    "apellido": "facu",
    "password": "susPassword"
}



###
@name login
POST {{BaseUrl}}/api/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "facu@example.com",
    "password": "susPassword"
}

###

### 
GET {{BaseUrl}}/api/vehiculos?desde=2025-10-01&hasta=2025-12-01
Accept: application/json
Authorization: Bearer {{login.response.body.*}}